from core.models import Category, Event
from django.utils import timezone
from datetime import timedelta

# Delete existing data
Category.objects.all().delete()
Event.objects.all().delete()

# Create categories
Category.objects.bulk_create(
    [
        Category(name="Entertainment", icon="controller"),
        Category(name="Travelling", icon="geo-alt"),
        Category(name="Community", icon="people"),
        Category(name="Cinema & Theater", icon="film"),
        Category(name="Nightlife", icon="moon"),
        Category(name="Trade Fairs & Expo", icon="shop"),
        Category(name="Professional", icon="briefcase"),
        Category(name="Sports", icon="trophy"),
        Category(name="Technology", icon="cpu"),  # Added Technology category
        Category(name="Others", icon="three-dots"),
    ]
)

# Get current time
now = timezone.now()

# Create events
Event.objects.bulk_create(
    [
        # Technology events
        Event(
            title="Nervtek Communities Challenge",
            slug="nervtek-challenge",
            description="Annual hackathon bringing together tech enthusiasts to solve community problems",
            datetime=now + timedelta(days=15),
            location_type="onsite",
            location="Yaoundé Conference Center",
            category=Category.objects.get(name="Technology"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="IndabaX Cameroon",
            slug="indabax-cameroon",
            description="Local version of the Deep Learning Indaba focusing on AI research and applications",
            datetime=now + timedelta(days=30),
            location_type="hybrid",
            location="University of Buea",
            category=Category.objects.get(name="Technology"),
            price_amount=10000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Camtel Blue Innovation Summit",
            slug="camtel-blue-summit",
            description="Showcase of cutting-edge telecom innovations and digital solutions",
            datetime=now + timedelta(days=45),
            location_type="onsite",
            location="Hilton Yaoundé",
            category=Category.objects.get(name="Technology"),
            price_amount=25000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Silicon Mountain Meetup",
            slug="silicon-mountain-meetup",
            description="Monthly gathering of tech entrepreneurs and developers in Buea",
            datetime=now + timedelta(days=7),
            location_type="onsite",
            location="ActivSpaces Buea",
            category=Category.objects.get(name="Technology"),
            price_amount=5000,
            price_currency="XAF",
            status=True,
        ),
        # Other events
        Event(
            title="Douala International Jazz Festival",
            slug="douala-jazz-festival",
            description="Annual celebration of jazz music with international artists",
            datetime=now - timedelta(days=3),
            location_type="onsite",
            location="Douala Maritime Museum",
            category=Category.objects.get(name="Entertainment"),
            price_amount=15000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Mount Cameroon Race of Hope",
            slug="mount-cameroon-race",
            description="Annual mountain race challenging athletes to summit Mount Cameroon",
            datetime=now + timedelta(days=20),
            location_type="onsite",
            location="Buea, Southwest Region",
            category=Category.objects.get(name="Sports"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Limbe Festival of Arts and Culture",
            slug="limbe-festival",
            description="Celebration of Cameroonian arts, culture and traditions",
            datetime=now + timedelta(days=60),
            location_type="onsite",
            location="Limbe Town",
            category=Category.objects.get(name="Community"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Yaoundé Fashion Week",
            slug="yaounde-fashion-week",
            description="Showcase of African fashion designers and models",
            datetime=now + timedelta(days=25),
            location_type="onsite",
            location="Yaoundé Mont Febe Hotel",
            category=Category.objects.get(name="Entertainment"),
            price_amount=20000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Bamenda Cultural Festival",
            slug="bamenda-festival",
            description="Traditional dances, food and crafts from Northwest region",
            datetime=now + timedelta(days=50),
            location_type="onsite",
            location="Bamenda Town Green",
            category=Category.objects.get(name="Community"),
            price_amount=5000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Cameroon International Trade Fair",
            slug="cameroon-trade-fair",
            description="Largest exhibition of businesses and products in Central Africa",
            datetime=now + timedelta(days=35),
            location_type="onsite",
            location="Douala Fair Grounds",
            category=Category.objects.get(name="Trade Fairs & Expo"),
            price_amount=3000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Maroua Camel Race",
            slug="maroua-camel-race",
            description="Traditional camel racing festival in the Far North region",
            datetime=now + timedelta(days=70),
            location_type="onsite",
            location="Maroua Stadium",
            category=Category.objects.get(name="Sports"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Kribi Beach Festival",
            slug="kribi-beach-festival",
            description="Music, food and sports on Cameroon's beautiful beaches",
            datetime=now + timedelta(days=40),
            location_type="onsite",
            location="Kribi Beach",
            category=Category.objects.get(name="Entertainment"),
            price_amount=10000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Cameroon Tech Summit",
            slug="cameroon-tech-summit",
            description="Gathering of tech professionals and entrepreneurs",
            datetime=now + timedelta(days=55),
            location_type="hybrid",
            location="Douala Digital Center",
            category=Category.objects.get(name="Technology"),
            price_amount=15000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Bafoussam Agricultural Show",
            slug="bafoussam-agri-show",
            description="Exhibition of agricultural products and equipment",
            datetime=now + timedelta(days=65),
            location_type="onsite",
            location="Bafoussam Exhibition Center",
            category=Category.objects.get(name="Trade Fairs & Expo"),
            price_amount=2000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Ebolowa Chocolate Festival",
            slug="ebolowa-chocolate-fest",
            description="Celebration of Cameroon's cocoa and chocolate production",
            datetime=now + timedelta(days=75),
            location_type="onsite",
            location="Ebolowa Town",
            category=Category.objects.get(name="Community"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Garoua International Folklore Festival",
            slug="garoua-folklore-fest",
            description="Traditional music and dance from across Africa",
            datetime=now + timedelta(days=80),
            location_type="onsite",
            location="Garoua Stadium",
            category=Category.objects.get(name="Entertainment"),
            price_amount=8000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Dschang University Open Day",
            slug="dschang-university-day",
            description="Showcase of university research and student projects",
            datetime=now + timedelta(days=28),
            location_type="onsite",
            location="University of Dschang",
            category=Category.objects.get(name="Professional"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Ngaoundéré Horse Festival",
            slug="ngaoundere-horse-fest",
            description="Traditional horse riding displays and competitions",
            datetime=now + timedelta(days=85),
            location_type="onsite",
            location="Ngaoundéré",
            category=Category.objects.get(name="Community"),
            price_amount=5000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Douala Startup Pitch Night",
            slug="douala-pitch-night",
            description="Entrepreneurs pitch their startups to investors",
            datetime=now + timedelta(days=12),
            location_type="onsite",
            location="Krystal Palace Douala",
            category=Category.objects.get(name="Professional"),
            price_amount=10000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Yaoundé International Film Festival",
            slug="yaounde-film-fest",
            description="Screening of African films and documentaries",
            datetime=now + timedelta(days=33),
            location_type="onsite",
            location="Yaoundé City Hall",
            category=Category.objects.get(name="Cinema & Theater"),
            price_amount=12000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Bamenda Tech Meetup",
            slug="bamenda-tech-meetup",
            description="Monthly gathering of tech enthusiasts in Bamenda",
            datetime=now + timedelta(days=17),
            location_type="onsite",
            location="Bamenda Tech Hub",
            category=Category.objects.get(name="Technology"),
            price_amount=3000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Kumba Trade Fair",
            slug="kumba-trade-fair",
            description="Regional business exhibition in Southwest Cameroon",
            datetime=now + timedelta(days=42),
            location_type="onsite",
            location="Kumba Town",
            category=Category.objects.get(name="Trade Fairs & Expo"),
            price_amount=2000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Buea Mountain Bike Challenge",
            slug="buea-bike-challenge",
            description="Mountain biking competition on Mount Cameroon slopes",
            datetime=now + timedelta(days=38),
            location_type="onsite",
            location="Buea Town",
            category=Category.objects.get(name="Sports"),
            price_amount=15000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Douala Night Market",
            slug="douala-night-market",
            description="Evening market with food, crafts and entertainment",
            datetime=now + timedelta(days=5),
            location_type="onsite",
            location="Douala Bonanjo",
            category=Category.objects.get(name="Nightlife"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Yaoundé Poetry Slam",
            slug="yaounde-poetry-slam",
            description="Competitive poetry performance event",
            datetime=now + timedelta(days=22),
            location_type="onsite",
            location="French Cultural Center Yaoundé",
            category=Category.objects.get(name="Entertainment"),
            price_amount=5000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Limbe Wildlife Photography Workshop",
            slug="limbe-photo-workshop",
            description="Professional wildlife photography training",
            datetime=now + timedelta(days=47),
            location_type="onsite",
            location="Limbe Wildlife Center",
            category=Category.objects.get(name="Professional"),
            price_amount=35000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Cameroon Developer Conference",
            slug="cameroon-dev-conf",
            description="Annual conference for software developers",
            datetime=now + timedelta(days=52),
            location_type="hybrid",
            location="Digital Transformation Center Yaoundé",
            category=Category.objects.get(name="Technology"),
            price_amount=20000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Foumban Royal Arts Festival",
            slug="foumban-arts-fest",
            description="Celebration of Bamoun kingdom arts and crafts",
            datetime=now + timedelta(days=67),
            location_type="onsite",
            location="Foumban Palace",
            category=Category.objects.get(name="Community"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Bertoua Cultural Night",
            slug="bertoua-cultural-night",
            description="Evening of traditional music and dance from East region",
            datetime=now + timedelta(days=58),
            location_type="onsite",
            location="Bertoua Community Center",
            category=Category.objects.get(name="Entertainment"),
            price_amount=7000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Douala Business Networking Breakfast",
            slug="douala-networking-breakfast",
            description="Monthly professional networking event",
            datetime=now + timedelta(days=10),
            location_type="onsite",
            location="Sawa Hotel Douala",
            category=Category.objects.get(name="Professional"),
            price_amount=15000,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="Cameroon AI & Data Science Meetup",
            slug="cameroon-ai-meetup",
            description="Discussion on artificial intelligence applications",
            datetime=now + timedelta(days=27),
            location_type="online",
            location="Virtual",
            category=Category.objects.get(name="Technology"),
            price_amount=0,
            price_currency="XAF",
            status=True,
        ),
        Event(
            title="African Film Premiere Night",
            slug="african-film-premiere",
            description="Exclusive screening of new African cinema productions",
            datetime=now,
            location_type="onsite",
            location="Sawa Cinema, Douala",
            category=Category.objects.get(name="Cinema & Theater"),
            price_amount=8000,
            price_currency="XAF",
            status=True,
        ),
    ]
)
