# Generated by Django 5.2 on 2025-04-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("icon", models.CharField(default="question-square", max_length=32)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "location_type",
                    models.TextField(
                        choices=[
                            ("onsite", "On Site"),
                            ("remote", "Remote"),
                            ("hybrid", "Hybrid"),
                        ],
                        default="onsite",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("price_amount", models.FloatField(default=0.0)),
                ("price_currency", models.CharField(default="XAF")),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
            ],
        ),
    ]
