# Generated by Django 5.2 on 2025-04-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("name",), "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-datetime",)},
        ),
        migrations.RemoveField(
            model_name="event",
            name="category",
        ),
        migrations.AddField(
            model_name="event",
            name="categories",
            field=models.ManyToManyField(to="core.category"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
