# Generated by Django 5.2 on 2025-04-22 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_category_options_alter_event_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="categories",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.category",
            ),
            preserve_default=False,
        ),
    ]
