name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - GenjiruSUchiwa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - latest (Default)
        - develop (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET version
      description: What version of dotnet are you running?
      options:
        - 8.0.* (Default)
        - 9.0.* (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Also tell us how can we reproduce the bug?
      placeholder: Tell us steps to reproduce!
      value: "1. A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: What is the expected behaviour?
      placeholder: Describe the happy path for this feature!
      value: "Hello world!"
    validations:
      required: true
  - type: textarea
    id: possible-causes
    attributes:
      label: Possible causes
      description: What do you think is happening?
      placeholder: Describe  the possible causes of the bug.
      value: "Network issue!"
    validations:
      required: true
  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible solutions
      description: Can you provide some solutions or ideas to solve the issue?
      placeholder: Describe  the possible solutions for the bug.
      value: "Restart te router!"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide additional context or informations?
      placeholder: Provide some links or referrals.
      value: "Wikipedia always!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
