name: .NET 9 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install linting tools
        run: |
          dotnet tool restore
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish build artefact
        run: dotnet publish --configuration Release --output ./output
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./output

  unit_tests:
    runs-on: ubuntu-latest
    needs: [lint, build ]
    steps:
      - name: Download build artefact
        uses: actions/download-artifact@v3
        with:
          name: app-build
          path: ./output

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build --no-restore --filter "Category=Unit"

  integration_tests:
    runs-on: ubuntu-latest
    needs: [lint, build ]
    steps:
      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./output

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Run integration tests
        run: dotnet test --configuration Release --no-build --no-restore --filter "Category=Integration"
