name: Build and Test

on: [ workflow_dispatch, push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: "Verify working directory"
        run: ls -R

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install linting tools
        run: |
          dotnet tool restore
      - name: Validate code linter with Csharpier
        run: |
          dotnet dotnet-csharpier --check .
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore  --configuration Release
        
      - name: Upload build artefact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./bin/Release

  unit_tests:
    runs-on: ubuntu-latest
    needs: [lint, build ]
    steps:
      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: app-build
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: "Verify working directory"
        run: ls -R
        
      - name: Run unit tests
        run: dotnet test --filter "Category=Unit" --verbosity normal ./bin/Release

  integration_tests:
    runs-on: ubuntu-latest
    needs: [ lint, build, unit_tests ]
    steps:
      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: "Verify working directory"
        run: ls -R
        
      - name: Run unit tests
        run: dotnet test --filter "Category=Integration" --verbosity normal ./bin/Release