name: CI lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff djlint
      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: |
          ruff format --check place
          ruff check --output-format=github place
      - name: Run Djlint
        run: djlint --check place
