name: publish

on:
  push:
    branches: [ develop ]

env:
  DOTNET_VERSION: '9.0.100'
  APP_NAME: Place.API
  SOLUTION: Place.sln
  API_PROJECT: src/Place.API/Place.API.csproj

jobs:
  publish:
    strategy:
      matrix:
        os: [macos-latest ]
        include:
          - os: macos-latest
            runtime: osx
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Build and Test
      - name: Restore dependencies
        run: make restore SOLUTION=${{ env.SOLUTION }}

      - name: Build solution
        run: make build SOLUTION=${{ env.SOLUTION }}

      - name: Run unit tests
        run: make test-unit SOLUTION=${{ env.SOLUTION }}

      - name: Run integration tests
        run: make test-integration SOLUTION=${{ env.SOLUTION }}

      # Publish binaries
      - name: Publish x64
        run: make publish RUNTIME=${{ matrix.runtime }} API_PROJECT=${{ env.API_PROJECT }} APP_NAME=${{ env.APP_NAME }}
        env:
          PUBLISH_OUTPUT: ./publish/arm64