# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: osscameroon/place-api/.github/workflows/build.yml@main
  tests:
    needs: build
    uses: osscameroon/place-api/.github/workflows/tests.yml@main
  release:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for semantic-release to analyze commits
          

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog 
        env:
          GITHUB_TOKEN: ${{ secrets.PLACE_GITHUB_TOKEN }}
