# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow-build:
    uses: osscameroon/place-api/.github/workflows/build.yml@main
